"""edit model applydate

Revision ID: 408fca96d69a
Revises: b876236f9e0c
Create Date: 2024-09-04 12:58:11.425136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408fca96d69a'
down_revision = 'b876236f9e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('apply_date',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('apply_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
