"""Update updated_at to DateTime

Revision ID: 650e326bff48
Revises: 
Create Date: 2024-09-03 16:44:38.321667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650e326bff48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
