"""user register fixed

Revision ID: 92df08a4e15a
Revises: 
Create Date: 2024-09-25 18:52:27.934591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92df08a4e15a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
