"""Removed rejected model for better function

Revision ID: b876236f9e0c
Revises: 650e326bff48
Create Date: 2024-09-04 12:45:24.435889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b876236f9e0c'
down_revision = '650e326bff48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('role', sa.VARCHAR(length=120), nullable=False),
    sa.Column('city', sa.VARCHAR(length=80), nullable=False),
    sa.Column('link', sa.VARCHAR(length=120), nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=120), nullable=True),
    sa.Column('apply_date', sa.VARCHAR(length=80), nullable=False),
    sa.Column('rejected_at', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###
