"""edit model applydate

Revision ID: e8d0cce31b34
Revises: 408fca96d69a
Create Date: 2024-09-04 13:01:34.982216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d0cce31b34'
down_revision = '408fca96d69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('apply_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('apply_date',
               existing_type=sa.String(length=80),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
