"""Change apply_date format

Revision ID: f6929275c8ea
Revises: f81a9a9c2393
Create Date: 2024-09-04 15:01:51.637742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6929275c8ea'
down_revision = 'f81a9a9c2393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('apply_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('apply_date',
               existing_type=sa.String(length=80),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
