"""Change apply_date to DateTime

Revision ID: f81a9a9c2393
Revises: e8d0cce31b34
Create Date: 2024-09-04 14:50:04.859488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81a9a9c2393'
down_revision = 'e8d0cce31b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('apply_date',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('apply_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
